config/routes.rb
Trenderio::Application.routes.draw do
  resources :stories

  root 'stories#index'

  

end

app/models/story.rb
class Story < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.order('rating DESC').all
  end

  # # GET /stories/1
  # # GET /stories/1.json
  # def show
  # end

  # # GET /stories/new
  # def new
  #   @story = Story.new
  # end

  # # GET /stories/1/edit
  # def edit
  # end

  # # POST /stories
  # # POST /stories.json
  # def create
  #   @story = Story.new(story_params)

  #   respond_to do |format|
  #     if @story.save
  #       format.html { redirect_to @story, notice: 'Story was successfully created.' }
  #       format.json { render action: 'show', status: :created, location: @story }
  #     else
  #       format.html { render action: 'new' }
  #       format.json { render json: @story.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /stories/1
  # # PATCH/PUT /stories/1.json
  # def update
  #   respond_to do |format|
  #     if @story.update(story_params)
  #       format.html { redirect_to @story, notice: 'Story was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: 'edit' }
  #       format.json { render json: @story.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /stories/1
  # # DELETE /stories/1.json
  # def destroy
  #   @story.destroy
  #   respond_to do |format|
  #     format.html { redirect_to stories_url }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:title, :extract, :image, :time, :rating, :url, :categories)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>trender.io</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, user-scalable=no">
</head>
<body>
<div class="page-wrap">
	<div class="left-bar">
		<h1>trender<span class="io">.io</span></h1>
		<h4>the top news from<br/>the best sources</h4>
		<ul class="cats nav nav-stacked">
			<li><a class="l1" id="index" href="/#/">worldwide</a></li>
			<li><a class="l3" id="cat-news" href="/#/cat/news">news</a></li>
			<li><a class="l4" id="cat-sport" href="/#/cat/sport">sport</a></li>
			<li><a class="l5" id="cat-tech" href="/#/cat/tech">tech</a></li>
		</ul>
		<div class="last-updated">Last updated <span class="time"></span></strong></div>
		<div class="bottom-links">
		<ul class="nav nav-stacked bottom">
			<li><a class="l1" id="about" href="/#/about">about trender.io</a></li>
			<li><a class="l2" id="github" href="http://github.com/trender-io" target="_blank">github</a></li>
			<li><a class="l3" id="notebook" href="http://nbviewer.ipython.org/github/trender-io/report/blob/master/trender-io.ipynb" target="_blank">notebook</a></li>
			<li><a class="l4" id="videos" href="/#/videos">videos</a></li>
		</ul>
		</div>
	</div>
	<div class="main-area"><%= yield %></div>
</div>
</body>
</html>

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :extract %><br>
    <%= f.text_field :extract %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<div id="stories"></div>

<script type="text/javascript">
  $(function() {
    // Blog is the app name
    window.router = new Trenderio.Routers.StoriesRouter({stories: <%= @stories.to_json.html_safe -%>});
    if (!Backbone.History.started) {
    	Backbone.history.start();

    }
    
  });
</script>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @story.title %>
</p>

<p>
  <strong>Extract:</strong>
  <%= @story.extract %>
</p>

<p>
  <strong>Image:</strong>
  <%= @story.image %>
</p>

<p>
  <strong>Time:</strong>
  <%= @story.time %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @story.rating %>
</p>

<p>
  <strong>Url:</strong>
  <%= @story.url %>
</p>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>